### ISSUE TITLE
This doesn't work with current golang mobile repo.

### ISSUE THREAD

**Issue by Splizard** [rakyll/al#1]
Multiple definition of JNI_OnLoad.

```
/usr/local/android-ndk-r9d/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: error: /var/tmp/go-link-frORoA/000002.o: multiple definition of 'JNI_OnLoad'
/usr/local/android-ndk-r9d/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: /var/tmp/go-link-frORoA/000001.o: previous definition here
collect2: ld returned 1 exit status
```

I suspect it's interfering with the mobile's app package android.c
Is there a way to merge the OnLoad's? I don't know much about the android NDK but I'd love to get sound working with a game :+1:

**Comment by rakyll** [comment]
I have another pending CL that adds the OpenAL bindings to the mobile, let's keep the conversation there.

https://go-review.googlesource.com/#/c/3115/

**Comment by rakyll** [comment]
Having linked to the CL, I forgot to add that we have moved away from the idea to build the OpenAL from the source. This issue is going to be absolute soon. We will require user to link against an OpenAL library that is built for Android.
